### ISSUE TITLE
line break send message

### ISSUE THREAD

**Issue by saulolago** [RobertGrubb/codeigniter-slack-library#3]
How to break the line in the message?

**Comment by RobertGrubb** [comment]
I believe it's as simple as adding `\r\n` where you want the line break to happen. Let me know!

**Comment by saulolago** [comment]
did not work. Slack returned like this: "Olá, temos um novo contato.\r\nNome: Saulo".

Test like this: $this->slack->send('Olá, temos um novo contato.\r\nNome: Saulo')

**Comment by RobertGrubb** [comment]
Could that potentially be because of using single quotes? Maybe try wrapping the string in double quotes, keeping everything else the same. If that doesn't work, maybe also use `PHP_EOL` instead of `\r\n`

**Comment by saulolago** [comment]
The problem was in the quotes.
So it worked here: $this->slack->send("Olá, temos um novo contato.\nNome: Saulo")
Thank you very much.

**Comment by RobertGrubb** [comment]
@saulolago Glad you got it fixed!
